### ISSUE TITLE
Possible bug regarding default value

### ISSUE THREAD

**Issue by kkriisgaard** [EricZimmerman/Registry#6]
I've been working with the library for some time, and I stumbled upon a rather odd edge case: It is possible for a registry key to be named "(Default)".

Unless I've misunderstood your code, the default value gets named "(default)", which can lead to ambiguity in the odd case that a different value is explicitly named "(default)". 

https://github.com/EricZimmerman/Registry/blob/930dc98ecabe8b3d0990aa91ada9f6080dd8f949/Registry/Cells/VKCellRecord.cs#L573

If I'm right, I also have a suggestion, though it might take some time: Mark the value as default in a different manner, e.g. a DefaultVaule flag.

**Comment by EricZimmerman** [comment]
my code works the same as regedit does, ie if a value has no name, its name becomes "(default)"

i dont see what the issue is though due to the fact that the value name would be the same either way. if you wanted to see if it was due to the fact there was no value name, you can look at the technical details report for the key the value lives in which would show you whether there was a value name length or not (in addition to being able to see the actual value name in the vk record as well.

adding a flag like that would only result in it showing up in the technical details view anyways.
